# Generated by Django 4.2.5 on 2024-01-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_courses_alter_department_image_new_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_course',
            name='course',
        ),
        migrations.RemoveField(
            model_name='new_course',
            name='department',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='new_course',
        ),
    ]
